/*******************************************************************/
/* The following program was generated by the 'SAS2ING.SAS' pgm.   */
/* This is an Structured Querey Language (SQL) program.            */
/* The purpose of this program is to create and load an SQL table  */
/*   from an ASCII (TEXT) file (also generated by 'SAS2DB.SAS'     */
/* This code is generated specifically for Ingres SQL,             */
/* NOTE: Some modifications may be required.                       */
/*       Lines containing '\p' and '\g' are for Ingres Batch.      */
/*       f8 storage class is used for all numeric variables.       */
/*       (Storage clases can be modified if space is a problem)    */
/*       [location=()] and [from 'filename'] statements can change */
/*******************************************************************/

set autocommit on \g

create table PUMS905P (
     POWSTATE char(2) with null,
     PWGT1 char(4) with null,
     SERIALNO char(7) with null
)
with duplicates,
location = (ii_database)
\p\g

copy PUMS905P (
     POWSTATE= c0tab with null ('NULL'),
     PWGT1= c0tab with null ('NULL'),
     SERIALNO= c0nl with null ('NULL'),
     nl= d1)
from '/ftp/pub/tmp/98111315-2/pums905p.dat'
\p\g
